// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package api

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson31304c5DecodeGithubComBlackplayertenIdealVisualBackendApi(in *jlexer.Lexer, out *UploadedPath) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "path":
			out.Path = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson31304c5EncodeGithubComBlackplayertenIdealVisualBackendApi(out *jwriter.Writer, in UploadedPath) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"path\":"
		out.RawString(prefix[1:])
		out.String(string(in.Path))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UploadedPath) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson31304c5EncodeGithubComBlackplayertenIdealVisualBackendApi(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UploadedPath) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson31304c5EncodeGithubComBlackplayertenIdealVisualBackendApi(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UploadedPath) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson31304c5DecodeGithubComBlackplayertenIdealVisualBackendApi(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UploadedPath) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson31304c5DecodeGithubComBlackplayertenIdealVisualBackendApi(l, v)
}
